export class Case{
    date?:Date;
    list?:string;
    school_name?:string;
    problem_name?:string;
    howtofix?:string;
    crud?:string;
    shop?:string;
    cashier?:string;
    user?:string;
    recommend?:string;
    gate_notworking?:string;
    time_program_system?:string;
    attendance? :string;
    infomation_student_register?:string;
    homeroom?:string;
    visit_home?:string;
    sdq_eq?:string;
    person?:string;
    public_relations?:string;
    hybrid_classroom?:string;
    ai_classroom?:string;
    digital_resource_center?:string;
    recruiting?:string;
    libraly_digital?:string;
    synce?:string;
    internet_gate?:string;
    internet_person?:string;
    internet_food?:string;
    network_lan?:string;
    network_fiber?:string;
    bank_notsend?:string;
    DDNS?:string;
    import_data?:string;
    cloud?:string;
    picture?:string;
    start_system?:string;
    card_damaged?:string;
    remote_edit?:string;
    services?:string;
    openSystem_remote_edit?:string;
    openSystem_services?:string;
    report?:string;
    app?:string;
    make_card?:string;
    megvii?:string;
    hikvision?:string;
    gate747?:string;
    ip_camera?:string;
    ra_fr?:string;
    pc_MB_Raspherrypi?:string;
    ups?:string;
    tv?:string;
    server?:string;
    hub?:string;
    pipo?:string;
    customer_display?:string;
    rfid?:string;
    top_up_cupboard?:string;
    smart_plug?:string;
    complete?:string;
    follow?:string;
    wiriya?:string;
    pookpak?:string;
    komin?:string;
    greet?:string;
    short_id?:string;
    school_undefine?:string;
    tag_undefine?:string;
    howtofix_undefine?:string;
    user_undefine?:string
    constructor(
        date=new Date(),
        list="",
        school_name="",
        problem_name="",
        howtofix?:string,
        crud="",
        shop="",
        cashier="",
        user="",
        recommend="",
        gate_notworking="",
        time_program_system="",
        attendance :string="",
        infomation_student_register="",
        homeroom="",
        visit_home="",
        sdq_eq="",
        person="",
        public_relations="",
        hybrid_classroom="",
        ai_classroom_string="",
        digital_resource_center="",
        recruiting="",
        libraly_digital="",
        synce="",
        internet_gate="",
        internet_person="",
        internet_food="",
        network_lan="",
        network_fiber="",
        bank_notsend="",
        DDNS="",
        import_data="",
        cloud="",
        picture="",
        start_system="",
        card_damaged="",
        remote_edit="",
        services="",
        openSystem_remote_edit="",
        openSystem_services="",
        report="",
        app="",
        make_card="",
        megvii="",
        hikvision="",
        gate747="",
        ip_camera="",
        ra_fr="",
        pc_MB_Raspherrypi="",
        ups="",
        tv="",
        server="",
        hub="",
        pipo="",
        customer_display="",
        rfid="",
        top_up_cupboard="",
        smart_plug="",
        complete="",
        follow="",
        wiriya="",
        pookpak="",
        komin="",
        greet="", 
        short_id="",
        school_undefine="",
        tag_undefine="",
        howtofix_undefine="",
        user_undefine=""
    ){
this.date=date,
this.list=list,
this.school_name=school_name,
this.problem_name=problem_name,
this.howtofix=howtofix,
this.crud=crud,
this.shop=shop,
this.cashier=cashier,
this.user=user,
this.recommend=recommend,
this.gate_notworking=gate_notworking,
this.time_program_system=time_program_system,
this.attendance=attendance,
this.infomation_student_register=infomation_student_register,
this.homeroom=homeroom,
this.visit_home=visit_home,
this.sdq_eq=sdq_eq,
this.person=person,
this.public_relations=public_relations,
this.hybrid_classroom=hybrid_classroom,
this.ai_classroom=ai_classroom_string,
this.digital_resource_center=digital_resource_center,
this.recruiting=recruiting,
this.libraly_digital=libraly_digital,
this.synce=synce,
this.internet_gate=internet_gate,
this.internet_person=internet_person,
this.internet_food=internet_food,
this.network_lan=network_lan,
this.network_fiber=network_fiber,
this.bank_notsend=bank_notsend,
this.DDNS=DDNS,
this.import_data=import_data,
this.cloud=cloud,
this.picture=picture,
this.start_system=start_system,
this.card_damaged=card_damaged,
this.remote_edit=remote_edit,
this.openSystem_remote_edit=openSystem_remote_edit,
this.openSystem_services=openSystem_services,
this.services=services,
this.report=report,
this.app=app,
this.make_card=make_card,
this.megvii=megvii,
this.hikvision=hikvision,
this.gate747=gate747,
this.ip_camera=ip_camera,
this.ra_fr=ra_fr,
this.pc_MB_Raspherrypi=pc_MB_Raspherrypi,
this.ups=ups,
this.tv=tv,
this.server=server,
this.hub=hub,
this.pipo=pipo,
this.customer_display=customer_display,
this.rfid=rfid,
this.top_up_cupboard=top_up_cupboard,
this.smart_plug=smart_plug,
this.complete=complete,
this.follow=follow,
this.wiriya=wiriya,
this.pookpak=pookpak,
this.komin=komin
this.greet=greet,
this.short_id=short_id,
this.school_undefine = school_undefine,
this.tag_undefine = tag_undefine,
this.howtofix_undefine = howtofix_undefine,
this.user_undefine=user_undefine
    }
}